---
services:
  mysite:
    image: mywebs
    build: ./mysite
    ports:
      - "9001:80"
  dive:
    image: wagoodman/dive
    command: mywebs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# docker compose build mysite
# docker compose run dive 
  # one-off run!
  # tab to right and Ctrl+U to hide unmodified
  # tab back to left and ensure Ctrl+L not Ctrl+A (Aggregate changes) - diff per layer!

# curl localhost:9001
# curl lan_or_wan_ip:9001 # fails
  # recreate without 127.0.0.1 ip binding limit
  # test both - notice firewall prompt (if you are running one!)